/**
 * JarBoxProject - https://github.com/claudio-tortorelli/JarBox/
 *
 * MIT License - 2021
 */
package claudiosoft.jarbox;

/**
 * A convenient Java exception to identify errors generated by JarBox
 */
public class JarBoxException extends Exception {

    public JarBoxException(String errorMessage) {
        super(errorMessage);
    }

    public JarBoxException(String errorMessage, Throwable ex) {
        super(errorMessage, ex);
    }
}
